<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Version>1.13.0</Version>
    <Product>ToSic.Imageflow.Oqtane</Product>
    <Authors>2sic</Authors>
    <Company>2sic</Company>
    <Description>Imageflow.NET Server image processing and optimizing middleware with querystring API for Oqtane 6</Description>
    <Copyright>2sic</Copyright>
    <AssemblyName>ToSic.Imageflow.Oqt.Server.Oqtane</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;NU1701</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Imageflow.Server" Version="0.9.0" />
    <PackageReference Include="Imageflow.Server.HybridCache" Version="0.9.0" />
    <PackageReference Include="Imageflow.AllPlatforms" Version="0.15.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oqtane.Client" Version="6.0.1" />
    <PackageReference Include="Oqtane.Server" Version="6.0.1" />
    <PackageReference Include="Oqtane.Shared" Version="6.0.1" />
  </ItemGroup>
</Project>
